/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/detail_umbrellaDetailed.glb')
  const instances = useMemo(
    () => ({
      MeshdetailumbrellaDetailed: nodes.Mesh_detail_umbrellaDetailed,
      MeshdetailumbrellaDetailed1: nodes.Mesh_detail_umbrellaDetailed_1,
      MeshdetailumbrellaDetailed2: nodes.Mesh_detail_umbrellaDetailed_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/detail_umbrellaDetailed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshdetailumbrellaDetailed />
      <instances.MeshdetailumbrellaDetailed1 />
      <instances.MeshdetailumbrellaDetailed2 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/detail_umbrellaDetailed.glb')
