/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/large_buildingA.glb')
  const instances = useMemo(
    () => ({
      MeshlargebuildingA: nodes.Mesh_large_buildingA,
      MeshlargebuildingA1: nodes.Mesh_large_buildingA_1,
      MeshlargebuildingA2: nodes.Mesh_large_buildingA_2,
      MeshlargebuildingA3: nodes.Mesh_large_buildingA_3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/large_buildingA.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshlargebuildingA />
      <instances.MeshlargebuildingA1 />
      <instances.MeshlargebuildingA2 />
      <instances.MeshlargebuildingA3 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/large_buildingA.glb')
