/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/large_buildingG.glb')
  const instances = useMemo(
    () => ({
      MeshlargebuildingG: nodes.Mesh_large_buildingG,
      MeshlargebuildingG1: nodes.Mesh_large_buildingG_1,
      MeshlargebuildingG2: nodes.Mesh_large_buildingG_2,
      MeshlargebuildingG3: nodes.Mesh_large_buildingG_3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/large_buildingG.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshlargebuildingG />
      <instances.MeshlargebuildingG1 />
      <instances.MeshlargebuildingG2 />
      <instances.MeshlargebuildingG3 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/large_buildingG.glb')
