/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/large_buildingE.glb')
  const instances = useMemo(
    () => ({
      MeshlargebuildingE: nodes.Mesh_large_buildingE,
      MeshlargebuildingE1: nodes.Mesh_large_buildingE_1,
      MeshlargebuildingE2: nodes.Mesh_large_buildingE_2,
      MeshlargebuildingE3: nodes.Mesh_large_buildingE_3,
      MeshlargebuildingE4: nodes.Mesh_large_buildingE_4,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/large_buildingE.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshlargebuildingE />
      <instances.MeshlargebuildingE1 />
      <instances.MeshlargebuildingE2 />
      <instances.MeshlargebuildingE3 />
      <instances.MeshlargebuildingE4 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/large_buildingE.glb')
