/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/large_buildingF.glb')
  const instances = useMemo(
    () => ({
      MeshlargebuildingF: nodes.Mesh_large_buildingF,
      MeshlargebuildingF1: nodes.Mesh_large_buildingF_1,
      MeshlargebuildingF2: nodes.Mesh_large_buildingF_2,
      MeshlargebuildingF3: nodes.Mesh_large_buildingF_3,
      MeshlargebuildingF4: nodes.Mesh_large_buildingF_4,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/large_buildingF.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshlargebuildingF />
      <instances.MeshlargebuildingF1 />
      <instances.MeshlargebuildingF2 />
      <instances.MeshlargebuildingF3 />
      <instances.MeshlargebuildingF4 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/large_buildingF.glb')
