/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/sign_billboard.glb')
  const instances = useMemo(
    () => ({
      Meshsignbillboard: nodes.Mesh_sign_billboard,
      Meshsignbillboard1: nodes.Mesh_sign_billboard_1,
      Meshsignbillboard2: nodes.Mesh_sign_billboard_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/sign_billboard.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.Meshsignbillboard />
      <instances.Meshsignbillboard1 />
      <instances.Meshsignbillboard2 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/sign_billboard.glb')
