/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/skyscraperA.glb')
  const instances = useMemo(
    () => ({
      MeshskyscraperA: nodes.Mesh_skyscraperA,
      MeshskyscraperA1: nodes.Mesh_skyscraperA_1,
      MeshskyscraperA2: nodes.Mesh_skyscraperA_2,
      MeshskyscraperA3: nodes.Mesh_skyscraperA_3,
      MeshskyscraperA4: nodes.Mesh_skyscraperA_4,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/skyscraperA.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshskyscraperA />
      <instances.MeshskyscraperA1 />
      <instances.MeshskyscraperA2 />
      <instances.MeshskyscraperA3 />
      <instances.MeshskyscraperA4 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/skyscraperA.glb')
