/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/skyscraperD.glb')
  const instances = useMemo(
    () => ({
      MeshskyscraperD: nodes.Mesh_skyscraperD,
      MeshskyscraperD1: nodes.Mesh_skyscraperD_1,
      MeshskyscraperD2: nodes.Mesh_skyscraperD_2,
      MeshskyscraperD3: nodes.Mesh_skyscraperD_3,
      MeshskyscraperD4: nodes.Mesh_skyscraperD_4,
      MeshskyscraperD5: nodes.Mesh_skyscraperD_5,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/skyscraperD.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshskyscraperD />
      <instances.MeshskyscraperD1 />
      <instances.MeshskyscraperD2 />
      <instances.MeshskyscraperD3 />
      <instances.MeshskyscraperD4 />
      <instances.MeshskyscraperD5 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/skyscraperD.glb')
