/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/skyscraperB.glb')
  const instances = useMemo(
    () => ({
      MeshskyscraperB: nodes.Mesh_skyscraperB,
      MeshskyscraperB1: nodes.Mesh_skyscraperB_1,
      MeshskyscraperB2: nodes.Mesh_skyscraperB_2,
      MeshskyscraperB3: nodes.Mesh_skyscraperB_3,
      MeshskyscraperB4: nodes.Mesh_skyscraperB_4,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/skyscraperB.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshskyscraperB />
      <instances.MeshskyscraperB1 />
      <instances.MeshskyscraperB2 />
      <instances.MeshskyscraperB3 />
      <instances.MeshskyscraperB4 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/skyscraperB.glb')
