/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/small_buildingE.glb')
  const instances = useMemo(
    () => ({
      MeshsmallbuildingE: nodes.Mesh_small_buildingE,
      MeshsmallbuildingE1: nodes.Mesh_small_buildingE_1,
      MeshsmallbuildingE2: nodes.Mesh_small_buildingE_2,
      MeshsmallbuildingE3: nodes.Mesh_small_buildingE_3,
      MeshsmallbuildingE4: nodes.Mesh_small_buildingE_4,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/small_buildingE.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshsmallbuildingE />
      <instances.MeshsmallbuildingE1 />
      <instances.MeshsmallbuildingE2 />
      <instances.MeshsmallbuildingE3 />
      <instances.MeshsmallbuildingE4 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/small_buildingE.glb')
