/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/small_buildingB.glb')
  const instances = useMemo(
    () => ({
      MeshsmallbuildingB: nodes.Mesh_small_buildingB,
      MeshsmallbuildingB1: nodes.Mesh_small_buildingB_1,
      MeshsmallbuildingB2: nodes.Mesh_small_buildingB_2,
      MeshsmallbuildingB3: nodes.Mesh_small_buildingB_3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/small_buildingB.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshsmallbuildingB />
      <instances.MeshsmallbuildingB1 />
      <instances.MeshsmallbuildingB2 />
      <instances.MeshsmallbuildingB3 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/small_buildingB.glb')
