/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/small_buildingA.glb')
  const instances = useMemo(
    () => ({
      MeshsmallbuildingA: nodes.Mesh_small_buildingA,
      MeshsmallbuildingA1: nodes.Mesh_small_buildingA_1,
      MeshsmallbuildingA2: nodes.Mesh_small_buildingA_2,
      MeshsmallbuildingA3: nodes.Mesh_small_buildingA_3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/small_buildingA.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshsmallbuildingA />
      <instances.MeshsmallbuildingA1 />
      <instances.MeshsmallbuildingA2 />
      <instances.MeshsmallbuildingA3 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/small_buildingA.glb')
