/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/wall_windowF.glb')
  const instances = useMemo(
    () => ({
      MeshwallwindowF: nodes.Mesh_wall_windowF,
      MeshwallwindowF1: nodes.Mesh_wall_windowF_1,
      MeshwallwindowF2: nodes.Mesh_wall_windowF_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/wall_windowF.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshwallwindowF />
      <instances.MeshwallwindowF1 />
      <instances.MeshwallwindowF2 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/wall_windowF.glb')
