/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/wall_windowC.glb')
  const instances = useMemo(
    () => ({
      MeshwallwindowC: nodes.Mesh_wall_windowC,
      MeshwallwindowC1: nodes.Mesh_wall_windowC_1,
      MeshwallwindowC2: nodes.Mesh_wall_windowC_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/wall_windowC.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshwallwindowC />
      <instances.MeshwallwindowC1 />
      <instances.MeshwallwindowC2 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/wall_windowC.glb')
