/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/wall_doorB.glb')
  const instances = useMemo(
    () => ({
      MeshwalldoorB: nodes.Mesh_wall_doorB,
      MeshwalldoorB1: nodes.Mesh_wall_doorB_1,
      MeshwalldoorB2: nodes.Mesh_wall_doorB_2,
      MeshwalldoorB3: nodes.Mesh_wall_doorB_3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/wall_doorB.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshwalldoorB />
      <instances.MeshwalldoorB1 />
      <instances.MeshwalldoorB2 />
      <instances.MeshwalldoorB3 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/wall_doorB.glb')
