/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/detail_awning.glb')
  const instances = useMemo(
    () => ({
      Meshdetailawning: nodes.Mesh_detail_awning,
      Meshdetailawning1: nodes.Mesh_detail_awning_1,
      Meshdetailawning2: nodes.Mesh_detail_awning_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/detail_awning.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.Meshdetailawning />
      <instances.Meshdetailawning1 />
      <instances.Meshdetailawning2 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/detail_awning.glb')
