/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/detail_umbrella.glb')
  const instances = useMemo(
    () => ({
      Meshdetailumbrella: nodes.Mesh_detail_umbrella,
      Meshdetailumbrella1: nodes.Mesh_detail_umbrella_1,
      Meshdetailumbrella2: nodes.Mesh_detail_umbrella_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/detail_umbrella.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.Meshdetailumbrella />
      <instances.Meshdetailumbrella1 />
      <instances.Meshdetailumbrella2 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/detail_umbrella.glb')
