/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/detail_awningWide.glb')
  const instances = useMemo(
    () => ({
      MeshdetailawningWide: nodes.Mesh_detail_awningWide,
      MeshdetailawningWide1: nodes.Mesh_detail_awningWide_1,
      MeshdetailawningWide2: nodes.Mesh_detail_awningWide_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/detail_awningWide.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshdetailawningWide />
      <instances.MeshdetailawningWide1 />
      <instances.MeshdetailawningWide2 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/detail_awningWide.glb')
