/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/large_buildingC.glb')
  const instances = useMemo(
    () => ({
      MeshlargebuildingC: nodes.Mesh_large_buildingC,
      MeshlargebuildingC1: nodes.Mesh_large_buildingC_1,
      MeshlargebuildingC2: nodes.Mesh_large_buildingC_2,
      MeshlargebuildingC3: nodes.Mesh_large_buildingC_3,
      MeshlargebuildingC4: nodes.Mesh_large_buildingC_4,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/large_buildingC.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshlargebuildingC />
      <instances.MeshlargebuildingC1 />
      <instances.MeshlargebuildingC2 />
      <instances.MeshlargebuildingC3 />
      <instances.MeshlargebuildingC4 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/large_buildingC.glb')
