/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/sign_hospital.glb')
  const instances = useMemo(
    () => ({
      Meshsignhospital: nodes.Mesh_sign_hospital,
      Meshsignhospital1: nodes.Mesh_sign_hospital_1,
      Meshsignhospital2: nodes.Mesh_sign_hospital_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/sign_hospital.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.Meshsignhospital />
      <instances.Meshsignhospital1 />
      <instances.Meshsignhospital2 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/sign_hospital.glb')
