/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/skyscraperF.glb')
  const instances = useMemo(
    () => ({
      MeshskyscraperF: nodes.Mesh_skyscraperF,
      MeshskyscraperF1: nodes.Mesh_skyscraperF_1,
      MeshskyscraperF2: nodes.Mesh_skyscraperF_2,
      MeshskyscraperF3: nodes.Mesh_skyscraperF_3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/skyscraperF.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshskyscraperF />
      <instances.MeshskyscraperF1 />
      <instances.MeshskyscraperF2 />
      <instances.MeshskyscraperF3 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/skyscraperF.glb')
