/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/skyscraperE.glb')
  const instances = useMemo(
    () => ({
      MeshskyscraperE: nodes.Mesh_skyscraperE,
      MeshskyscraperE1: nodes.Mesh_skyscraperE_1,
      MeshskyscraperE2: nodes.Mesh_skyscraperE_2,
      MeshskyscraperE3: nodes.Mesh_skyscraperE_3,
      MeshskyscraperE4: nodes.Mesh_skyscraperE_4,
      MeshskyscraperE5: nodes.Mesh_skyscraperE_5,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/skyscraperE.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshskyscraperE />
      <instances.MeshskyscraperE1 />
      <instances.MeshskyscraperE2 />
      <instances.MeshskyscraperE3 />
      <instances.MeshskyscraperE4 />
      <instances.MeshskyscraperE5 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/skyscraperE.glb')
