/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/skyscraperC.glb')
  const instances = useMemo(
    () => ({
      MeshskyscraperC: nodes.Mesh_skyscraperC,
      MeshskyscraperC1: nodes.Mesh_skyscraperC_1,
      MeshskyscraperC2: nodes.Mesh_skyscraperC_2,
      MeshskyscraperC3: nodes.Mesh_skyscraperC_3,
      MeshskyscraperC4: nodes.Mesh_skyscraperC_4,
      MeshskyscraperC5: nodes.Mesh_skyscraperC_5,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/skyscraperC.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshskyscraperC />
      <instances.MeshskyscraperC1 />
      <instances.MeshskyscraperC2 />
      <instances.MeshskyscraperC3 />
      <instances.MeshskyscraperC4 />
      <instances.MeshskyscraperC5 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/skyscraperC.glb')
