/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/small_buildingF.glb')
  const instances = useMemo(
    () => ({
      MeshsmallbuildingF: nodes.Mesh_small_buildingF,
      MeshsmallbuildingF1: nodes.Mesh_small_buildingF_1,
      MeshsmallbuildingF2: nodes.Mesh_small_buildingF_2,
      MeshsmallbuildingF3: nodes.Mesh_small_buildingF_3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/small_buildingF.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshsmallbuildingF />
      <instances.MeshsmallbuildingF1 />
      <instances.MeshsmallbuildingF2 />
      <instances.MeshsmallbuildingF3 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/small_buildingF.glb')
