/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/wall_doorA.glb')
  const instances = useMemo(
    () => ({
      MeshwalldoorA: nodes.Mesh_wall_doorA,
      MeshwalldoorA1: nodes.Mesh_wall_doorA_1,
      MeshwalldoorA2: nodes.Mesh_wall_doorA_2,
      MeshwalldoorA3: nodes.Mesh_wall_doorA_3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/wall_doorA.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshwalldoorA />
      <instances.MeshwalldoorA1 />
      <instances.MeshwalldoorA2 />
      <instances.MeshwalldoorA3 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/wall_doorA.glb')
