/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/wall_windowA.glb')
  const instances = useMemo(
    () => ({
      MeshwallwindowA: nodes.Mesh_wall_windowA,
      MeshwallwindowA1: nodes.Mesh_wall_windowA_1,
      MeshwallwindowA2: nodes.Mesh_wall_windowA_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/wall_windowA.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshwallwindowA />
      <instances.MeshwallwindowA1 />
      <instances.MeshwallwindowA2 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/wall_windowA.glb')
