/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/models/kenney_city/wall_windowD.glb')
  const instances = useMemo(
    () => ({
      MeshwallwindowD: nodes.Mesh_wall_windowD,
      MeshwallwindowD1: nodes.Mesh_wall_windowD_1,
      MeshwallwindowD2: nodes.Mesh_wall_windowD_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kenney_city/wall_windowD.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <instances.MeshwallwindowD />
      <instances.MeshwallwindowD1 />
      <instances.MeshwallwindowD2 />
    </group>
  )
}

useGLTF.preload('/models/kenney_city/wall_windowD.glb')
