/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";
import * as THREE from "three";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/hidden/hidden.gltf");
  const { actions } = useAnimations(animations, group);
  console.log(actions);
  useEffect(() => {
    for (let action in actions) {
      let a = actions[action].play();
      a.setLoop(THREE.LoopOnce);
      a.clampWhenFinished = true;
      setInterval(() => {
        a.reset();
      }, 9000);
    }
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-2.15, 2.65, -1.47]}
        rotation={[2.67, -0.49, 2.8]}
        scale={0.3}
      >
        <pointLight
          intensity={1.5}
          decay={2}
          color="#97b9ff"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group
        position={[-0.38, 1.81, -0.63]}
        rotation={[-1.66, 0.04, 0.55]}
        scale={0.07}
      >
        <primitive object={nodes.topJoint} />
        <skinnedMesh
          geometry={nodes.BASE_Low_Poly_Man.geometry}
          material={materials.PropsPBR}
          skeleton={nodes.BASE_Low_Poly_Man.skeleton}
        />
        <skinnedMesh
          geometry={nodes.necklace.geometry}
          material={materials.PropsPBR_1}
          skeleton={nodes.necklace.skeleton}
        />
        <skinnedMesh
          geometry={nodes.chestpiece.geometry}
          material={materials.PropsPBR_2}
          skeleton={nodes.chestpiece.skeleton}
        />
        <skinnedMesh
          geometry={nodes.pauldrons.geometry}
          material={materials.PropsPBR_3}
          skeleton={nodes.pauldrons.skeleton}
        />
        <skinnedMesh
          geometry={nodes.helmet.geometry}
          material={materials.PropsPBR_4}
          skeleton={nodes.helmet.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Layer_6.geometry}
          material={materials.PropsPBR_5}
          skeleton={nodes.Layer_6.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Layer_7.geometry}
          material={materials.PropsPBR_6}
          skeleton={nodes.Layer_7.skeleton}
        />
      </group>
      <group
        position={[-0.69, 2.13, -1.68]}
        rotation={[0.08, 0.24, -0.03]}
        scale={3.93}
      >
        <PerspectiveCamera
          makeDefault={false}
          far={600000}
          near={20.13}
          fov={54.4}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          scale={[.01,.01,.01]}
          geometry={nodes.Layer_7.geometry}
          material={materials.PropsPBR_6}
        />
      </group>
      <group
        position={[-1.05, 2.15, -0.77]}
        rotation={[0.69, 1.31, -0.55]}
        scale={3.96}
      >
        <PerspectiveCamera
          makeDefault={false}
          far={600000}
          near={20.31}
          fov={54.4}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          scale={[.01,.01,.01]}
          geometry={nodes.Layer_7.geometry}
          material={materials.PropsPBR_6}
        />
      </group>
      <group
        position={[-0.25, 1.98, 0.15]}
        rotation={[3.11, -0.09, 3.1]}
        scale={8.97}
      >
        <PerspectiveCamera
          makeDefault={false}
          far={600000}
          near={46.01}
          fov={54.4}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          scale={[.01,.01,.01]}
          geometry={nodes.Layer_7.geometry}
          material={materials.PropsPBR_6}
        />
      </group>
      <group
        name="ToolCamera_(4)"
        position={[0.36, 1.64, -1.78]}
        rotation={[-0.32, -0.68, -0.37]}
        scale={8.68}
      >
        <PerspectiveCamera
          makeDefault={false}
          far={600000}
          near={44.49}
          fov={54.5}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          scale={[.01,.01,.01]}
          geometry={nodes.Layer_7.geometry}
          material={materials.PropsPBR_6}
        />
      </group>
      <directionalLight
        intensity={1}
        decay={2}
        color="#0fe0b7"
        rotation={[-2.04, 0.5, 2.04]}
        scale={[1.06, 1.06, 1.06]}
      />
    </group>
  );
}

useGLTF.preload("/hidden.gltf");
