/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('models/ruins2.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={[3,3,3]}>
      <mesh
        geometry={nodes.Mesh_0.geometry}
        material={materials.Material_0}
        position={[0.29, 3.07, -0.54]}
        rotation={[-1.57, -0.01, 0.91]}
      />
    </group>
  )
}

useGLTF.preload('models/ruins2.gltf')
